#+TITLE: Emjupy
#+author: Mathieu Renzo (with LLM help)

Jupyter notebooks with remote kernel execution using emacs built-ins
(=eglot= and =tramp=, completion frameworks like =vertico= + =corfu= +
=orderless=) while maintaining compatibility with standard =*.ipynb= for
sharing with non-emacs users.

* Features
- persistent kernel session (to load large dataset once and re-use
  them)
- in-line rendering of output including images
- automatic loading of kernel from port (either local port or remote
  provided from ssh-tunnel), and python environment (including for
  =eglot=), and lands to the notebook list, similar to
  =ein:notebooklist-login=
- resilient to connection drops (remote kernel keeps running,
  reconnect emacs)
- =ein=-like workflow and key bindings


* Try it with emacs -Q
To test this in an isolated environment without touching your current config:

1. Create a temporary directory:
   #+begin_src bash
   mkdir -p /tmp/
   #+end_src

2. Launch Emacs with:
   #+begin_src bash
   emacs -Q -L . -l quicktry.el
   #+end_src
   =-Q= ignores your setup of emacs, =-L .= installs *locally* the
   requirements (to not clutter your emacs installation).

3. Run =emjupy-connect= to be prompted for the port where the notebook
   is running (possibly through an ssh tunnel).

* Testing

To test the connectivity to the kernel, launch a kernel on port
=8.8.8.8= without password:

#+BEGIN_SRC bash
 jupyter-notebook --no-browser --port=8888 --IdentityProvider.token='abc' --NotebookApp.token='abc'
#+END_SRC

You can run the =emjupy= unit tests with:

#+begin_src bash
emacs -batch -Q -L . -l emjupy-run-tests.el
#+end_src


* Developing

Run the function =emjupy-login=, provide the port (e.g., =8.8.8.8=),
password or token, and then you should get a list of notebooks.
