name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: '30.1'

      - name: Check
        run: |
          make check

      - name: Package
        run: |
          make package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.tar'
